"""add versioned analysis snapshots

Revision ID: 138813db0d60
Revises: bc301a1cb285
Create Date: 2026-08-08 17:45:11.222085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "138813db0d60"
down_revision: str | Sequence[str] | None = "bc301a1cb285"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mart_analysis_context_snapshot",
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("dataset_version", sa.String(length=96), nullable=False),
        sa.Column("filters_json", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column(
            "refreshed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("scope_key"),
    )
    op.create_index(
        op.f("ix_mart_analysis_context_snapshot_dataset_version"),
        "mart_analysis_context_snapshot",
        ["dataset_version"],
        unique=False,
    )
    op.create_table(
        "system_data_version",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=96), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_data_version")
    op.drop_index(
        op.f("ix_mart_analysis_context_snapshot_dataset_version"),
        table_name="mart_analysis_context_snapshot",
    )
    op.drop_table("mart_analysis_context_snapshot")
    # ### end Alembic commands ###
