"""baseline hiring analytics schema

Revision ID: bc301a1cb285
Revises:
Create Date: 2026-08-08 17:44:53.603398

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc301a1cb285"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_candidate",
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("education_level", sa.String(length=32), nullable=False),
        sa.Column("current_title", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(op.f("ix_dim_candidate_region"), "dim_candidate", ["region"], unique=False)
    op.create_table(
        "dim_job",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("job_category", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("seniority_level", sa.String(length=32), nullable=False),
        sa.Column("opened_at", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_dim_job_job_category"), "dim_job", ["job_category"], unique=False)
    op.create_index(op.f("ix_dim_job_region"), "dim_job", ["region"], unique=False)
    op.create_table(
        "dim_model_version",
        sa.Column("model_version_id", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("deployed_at", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("model_version_id"),
    )
    op.create_index(
        op.f("ix_dim_model_version_model_version"),
        "dim_model_version",
        ["model_version"],
        unique=True,
    )
    op.create_table(
        "dim_recruiter",
        sa.Column("recruiter_id", sa.String(length=32), nullable=False),
        sa.Column("recruiter_name", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("team", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("recruiter_id"),
    )
    op.create_index(op.f("ix_dim_recruiter_region"), "dim_recruiter", ["region"], unique=False)
    op.create_table(
        "mart_ai_effectiveness",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_category", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("comparison_numerator", sa.Integer(), nullable=False),
        sa.Column("comparison_denominator", sa.Integer(), nullable=False),
        sa.Column("comparison_rate", sa.Float(), nullable=False),
        sa.Column("effect_size", sa.Float(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("data_origin", sa.String(length=32), nullable=False),
        sa.Column("metric_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "period_start",
            "period_end",
            "job_category",
            "region",
            "metric_name",
            "metric_version",
            name="uq_ai_effectiveness_segment_metric",
        ),
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_job_category"),
        "mart_ai_effectiveness",
        ["job_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_metric_name"),
        "mart_ai_effectiveness",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_metric_version"),
        "mart_ai_effectiveness",
        ["metric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_period_end"),
        "mart_ai_effectiveness",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_period_start"),
        "mart_ai_effectiveness",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_ai_effectiveness_region"), "mart_ai_effectiveness", ["region"], unique=False
    )
    op.create_table(
        "mart_cohort_conversion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cohort_month", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("job_category", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("data_origin", sa.String(length=32), nullable=False),
        sa.Column("metric_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cohort_month",
            "source",
            "job_category",
            "region",
            "metric_name",
            "metric_version",
            name="uq_cohort_conversion_segment_metric",
        ),
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_cohort_month"),
        "mart_cohort_conversion",
        ["cohort_month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_job_category"),
        "mart_cohort_conversion",
        ["job_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_metric_name"),
        "mart_cohort_conversion",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_metric_version"),
        "mart_cohort_conversion",
        ["metric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_period_end"),
        "mart_cohort_conversion",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_period_start"),
        "mart_cohort_conversion",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_region"), "mart_cohort_conversion", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_mart_cohort_conversion_source"), "mart_cohort_conversion", ["source"], unique=False
    )
    op.create_table(
        "mart_daily_funnel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("job_category", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("recommended", sa.Integer(), nullable=False),
        sa.Column("contacted", sa.Integer(), nullable=False),
        sa.Column("replied", sa.Integer(), nullable=False),
        sa.Column("interviewed", sa.Integer(), nullable=False),
        sa.Column("offered", sa.Integer(), nullable=False),
        sa.Column("hired", sa.Integer(), nullable=False),
        sa.Column("data_origin", sa.String(length=32), nullable=False),
        sa.Column("metric_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "metric_date",
            "source",
            "job_category",
            "region",
            "metric_name",
            "metric_version",
            name="uq_daily_funnel_segment",
        ),
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_job_category"),
        "mart_daily_funnel",
        ["job_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_metric_date"), "mart_daily_funnel", ["metric_date"], unique=False
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_metric_name"), "mart_daily_funnel", ["metric_name"], unique=False
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_metric_version"),
        "mart_daily_funnel",
        ["metric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_period_end"), "mart_daily_funnel", ["period_end"], unique=False
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_period_start"),
        "mart_daily_funnel",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_region"), "mart_daily_funnel", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_mart_daily_funnel_source"), "mart_daily_funnel", ["source"], unique=False
    )
    op.create_table(
        "mart_feature_drift",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feature_name", sa.String(length=64), nullable=False),
        sa.Column("segment", sa.String(length=64), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("baseline_rate", sa.Float(), nullable=False),
        sa.Column("current_rate", sa.Float(), nullable=False),
        sa.Column("drift_score", sa.Float(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("data_origin", sa.String(length=32), nullable=False),
        sa.Column("metric_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "feature_name",
            "segment",
            "period_start",
            "period_end",
            "metric_version",
            name="uq_feature_drift_metric",
        ),
    )
    op.create_index(
        op.f("ix_mart_feature_drift_feature_name"),
        "mart_feature_drift",
        ["feature_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_feature_drift_metric_name"),
        "mart_feature_drift",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_feature_drift_metric_version"),
        "mart_feature_drift",
        ["metric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_feature_drift_period_end"), "mart_feature_drift", ["period_end"], unique=False
    )
    op.create_index(
        op.f("ix_mart_feature_drift_period_start"),
        "mart_feature_drift",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_feature_drift_segment"), "mart_feature_drift", ["segment"], unique=False
    )
    op.create_table(
        "mart_monitoring_alert",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_key", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.String(length=512), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("data_origin", sa.String(length=32), nullable=False),
        sa.Column("metric_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_key", "metric_version", name="uq_monitoring_alert_key_version"),
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_alert_key"),
        "mart_monitoring_alert",
        ["alert_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_metric_name"),
        "mart_monitoring_alert",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_metric_version"),
        "mart_monitoring_alert",
        ["metric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_period_end"),
        "mart_monitoring_alert",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_period_start"),
        "mart_monitoring_alert",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_severity"),
        "mart_monitoring_alert",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mart_monitoring_alert_status"), "mart_monitoring_alert", ["status"], unique=False
    )
    op.create_table(
        "fact_recommendation",
        sa.Column("recommendation_id", sa.String(length=40), nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("recruiter_id", sa.String(length=32), nullable=False),
        sa.Column("model_version_id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("recommendation_score", sa.Float(), nullable=False),
        sa.Column("recommended_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["dim_candidate.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["dim_job.job_id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["dim_model_version.model_version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recruiter_id"],
            ["dim_recruiter.recruiter_id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_fact_recommendation_candidate_id"),
        "fact_recommendation",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_recommendation_job_id"), "fact_recommendation", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_fact_recommendation_model_version_id"),
        "fact_recommendation",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_recommendation_recommended_at"),
        "fact_recommendation",
        ["recommended_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_recommendation_recruiter_id"),
        "fact_recommendation",
        ["recruiter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_recommendation_source"), "fact_recommendation", ["source"], unique=False
    )
    op.create_table(
        "fact_funnel_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recommendation_id", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["fact_recommendation.recommendation_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint(
            "recommendation_id", "stage", name="uq_funnel_event_recommendation_stage"
        ),
    )
    op.create_index(
        op.f("ix_fact_funnel_event_event_at"), "fact_funnel_event", ["event_at"], unique=False
    )
    op.create_index(
        op.f("ix_fact_funnel_event_recommendation_id"),
        "fact_funnel_event",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fact_funnel_event_stage"), "fact_funnel_event", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_fact_funnel_event_status"), "fact_funnel_event", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fact_funnel_event_status"), table_name="fact_funnel_event")
    op.drop_index(op.f("ix_fact_funnel_event_stage"), table_name="fact_funnel_event")
    op.drop_index(op.f("ix_fact_funnel_event_recommendation_id"), table_name="fact_funnel_event")
    op.drop_index(op.f("ix_fact_funnel_event_event_at"), table_name="fact_funnel_event")
    op.drop_table("fact_funnel_event")
    op.drop_index(op.f("ix_fact_recommendation_source"), table_name="fact_recommendation")
    op.drop_index(op.f("ix_fact_recommendation_recruiter_id"), table_name="fact_recommendation")
    op.drop_index(op.f("ix_fact_recommendation_recommended_at"), table_name="fact_recommendation")
    op.drop_index(op.f("ix_fact_recommendation_model_version_id"), table_name="fact_recommendation")
    op.drop_index(op.f("ix_fact_recommendation_job_id"), table_name="fact_recommendation")
    op.drop_index(op.f("ix_fact_recommendation_candidate_id"), table_name="fact_recommendation")
    op.drop_table("fact_recommendation")
    op.drop_index(op.f("ix_mart_monitoring_alert_status"), table_name="mart_monitoring_alert")
    op.drop_index(op.f("ix_mart_monitoring_alert_severity"), table_name="mart_monitoring_alert")
    op.drop_index(op.f("ix_mart_monitoring_alert_period_start"), table_name="mart_monitoring_alert")
    op.drop_index(op.f("ix_mart_monitoring_alert_period_end"), table_name="mart_monitoring_alert")
    op.drop_index(
        op.f("ix_mart_monitoring_alert_metric_version"), table_name="mart_monitoring_alert"
    )
    op.drop_index(op.f("ix_mart_monitoring_alert_metric_name"), table_name="mart_monitoring_alert")
    op.drop_index(op.f("ix_mart_monitoring_alert_alert_key"), table_name="mart_monitoring_alert")
    op.drop_table("mart_monitoring_alert")
    op.drop_index(op.f("ix_mart_feature_drift_segment"), table_name="mart_feature_drift")
    op.drop_index(op.f("ix_mart_feature_drift_period_start"), table_name="mart_feature_drift")
    op.drop_index(op.f("ix_mart_feature_drift_period_end"), table_name="mart_feature_drift")
    op.drop_index(op.f("ix_mart_feature_drift_metric_version"), table_name="mart_feature_drift")
    op.drop_index(op.f("ix_mart_feature_drift_metric_name"), table_name="mart_feature_drift")
    op.drop_index(op.f("ix_mart_feature_drift_feature_name"), table_name="mart_feature_drift")
    op.drop_table("mart_feature_drift")
    op.drop_index(op.f("ix_mart_daily_funnel_source"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_region"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_period_start"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_period_end"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_metric_version"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_metric_name"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_metric_date"), table_name="mart_daily_funnel")
    op.drop_index(op.f("ix_mart_daily_funnel_job_category"), table_name="mart_daily_funnel")
    op.drop_table("mart_daily_funnel")
    op.drop_index(op.f("ix_mart_cohort_conversion_source"), table_name="mart_cohort_conversion")
    op.drop_index(op.f("ix_mart_cohort_conversion_region"), table_name="mart_cohort_conversion")
    op.drop_index(
        op.f("ix_mart_cohort_conversion_period_start"), table_name="mart_cohort_conversion"
    )
    op.drop_index(op.f("ix_mart_cohort_conversion_period_end"), table_name="mart_cohort_conversion")
    op.drop_index(
        op.f("ix_mart_cohort_conversion_metric_version"), table_name="mart_cohort_conversion"
    )
    op.drop_index(
        op.f("ix_mart_cohort_conversion_metric_name"), table_name="mart_cohort_conversion"
    )
    op.drop_index(
        op.f("ix_mart_cohort_conversion_job_category"), table_name="mart_cohort_conversion"
    )
    op.drop_index(
        op.f("ix_mart_cohort_conversion_cohort_month"), table_name="mart_cohort_conversion"
    )
    op.drop_table("mart_cohort_conversion")
    op.drop_index(op.f("ix_mart_ai_effectiveness_region"), table_name="mart_ai_effectiveness")
    op.drop_index(op.f("ix_mart_ai_effectiveness_period_start"), table_name="mart_ai_effectiveness")
    op.drop_index(op.f("ix_mart_ai_effectiveness_period_end"), table_name="mart_ai_effectiveness")
    op.drop_index(
        op.f("ix_mart_ai_effectiveness_metric_version"), table_name="mart_ai_effectiveness"
    )
    op.drop_index(op.f("ix_mart_ai_effectiveness_metric_name"), table_name="mart_ai_effectiveness")
    op.drop_index(op.f("ix_mart_ai_effectiveness_job_category"), table_name="mart_ai_effectiveness")
    op.drop_table("mart_ai_effectiveness")
    op.drop_index(op.f("ix_dim_recruiter_region"), table_name="dim_recruiter")
    op.drop_table("dim_recruiter")
    op.drop_index(op.f("ix_dim_model_version_model_version"), table_name="dim_model_version")
    op.drop_table("dim_model_version")
    op.drop_index(op.f("ix_dim_job_region"), table_name="dim_job")
    op.drop_index(op.f("ix_dim_job_job_category"), table_name="dim_job")
    op.drop_table("dim_job")
    op.drop_index(op.f("ix_dim_candidate_region"), table_name="dim_candidate")
    op.drop_table("dim_candidate")
    # ### end Alembic commands ###
